model_family: phi #phi llama2-7b
w_decay: 0.0
LoRA:
  r: 0
  alpha: 32
  dropout: 0.05

lr: 2e-5
split: forget01
data_path: locuslab/TOFU
batch_size: 4 #4
gradient_accumulation_steps: 4
num_epochs: 5 #5
forget_loss: grad_ascent
hyper_param: None

model_path: /data/weight/ft_epoch5_lr1e-05_llama2-7b_full_wd0.0/checkpoint-625
save_dir: iclr/${model_family}/${forget_loss}_${lr}_${split}_${num_epochs}_${w_decay}_${hyper_param}
save_steps: 25
overwrite_dir: True
weight_decay: 0.0
save_model: true
eval_while_train: false
eval_only: false
seed: 42

eval:
  # retain_result: data/retain90_llama_wd0.01/eval_results/ds_size300/eval_log_aggregated.json
  model_path: ${..model_path}
  model_family: ${..model_family}
  save_dir: ${..save_dir}
  data_path: [locuslab/TOFU, locuslab/TOFU, locuslab/TOFU, locuslab/TOFU]
  split: ${..split}_perturbed
  split_list:
    - retain_perturbed
    - real_authors_perturbed
    - world_facts_perturbed
    - ${split}

  eval_task: [eval_log, eval_real_author_wo_options, eval_real_world_wo_options, eval_log_forget]
  question_key: [question, question, question, question]
  answer_key: [answer, answer, answer, answer]
  base_answer_key: [paraphrased_answer, answer, answer, paraphrased_answer]
  perturbed_answer_key: [perturbed_answer, perturbed_answer, perturbed_answer, perturbed_answer]

  generation:
    max_length: 200
    max_new_tokens: null

  save_generated_text: true

  ds_size: 300

  overwrite: true
  use_pretrained: false

  batch_size: 30
  retain_result: null

strategy: false